<template>
  <!-- <VTooltip :disabled="!localError" class="ui-tooltip"> -->
    <div :class="['ui-input', { _disabled: disabled, _readonly: readonly }]">
      <!-- <label v-if="label" :for="id" class="ui-input__label">
        {{ label }}
      </label> -->
      <div class="ui-input__control-wrap">
        <input
          ref="input"
          :class="['ui-input__control', { _error: localError }]"
          :style="inputStyles"
          v-bind="computedAttrs"
          v-on="computedListeners"
          :placeholder="label"
        />

      </div>
    </div>
    <!-- <template #popper>
      <ul class="ui-tooltip__popper">
        <li
          v-for="{ $message, id } in localErrorMessages"
          :key="id"
          class="ui-tooltip-popper__error-message"
        >
          {{ $message }}
        </li>
      </ul>
    </template> -->
  <!-- </VTooltip> -->
</template>

<script>
// import createNumberMask from "text-mask-addons/dist/createNumberMask";
// import { VueMaskDirective } from "v-mask";
// import { isEmpty } from "lodash";
// import { v4 as uuidv4 } from "uuid";
// import UIButtonIcon from "@/components/ui/buttons/UIButtonIcon/index.vue";
// import { getFontSizes } from "@/utils/helpers/fontSize";

   const uuidv4 = () => {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
        const r = (Math.random() * 16) | 0,
            v = c === 'x' ? r : (r & 0x3) | 0x8;
        return v.toString(16);
    })
   }

export default {
  name: "UIInput",
  // components: {
  //   UIButtonIcon,
  // },
  inheritAttrs: false,
  props: {
    /**
     * extra input content. Common usage for postfixes (%, $, etc.)
     */
    appendText: {
      type: String,
      default: null,
    },
    /**
     * disable input
     */
    disabled: { type: Boolean, default: false },
    /**
     * custom error (for api validation errors or else validations)
     */
    error: { type: String, default: "" },
    /**
     * unique input id. Generated by default
     */
    id: { type: String, default: () => uuidv4() },
    /**
     * sets append icon
     */
    icon: { type: Object, default: null },
    /**
     * input label
     */
    label: { type: String, default: "" },
    /**
     * prop for v-mask https://github.com/probil/v-mask#readme
     */
    mask: { type: [String, Array, Object, Function], default: "" },
    /**
     * set input as readonly
     */
    readonly: { type: Boolean, default: false },
    /**
     * set input type
     */
    type: { type: String, default: "text" },
    /**
     * vuelidate validator object https://github.com/vuelidate/vuelidate#the-validation-object-aka-v-object
     */
    validator: { type: Object, default: null },
    /**
     * @model input value
     */
    value: { type: [String, Number], default: "" },
    /**
     * Error tooltip placement
     */
    errorPlacement: { type: String, default: "top-end" },
  },
  data() {
    return {
      localValue: this.value,
      paddingRight: 0,
    };
  },
  computed: {
    computedAttrs() {
      const { id, disabled, readonly, type, localValue } = this;
      return {
        disabled,
        id,
        readonly,
        type,
        value: localValue,
        ...this.$attrs,
      };
    },
    computedListeners() {
      const { onChange, onInput } = this;
      return {
        ...this.$attrs,
        input: onInput,
        change: onChange,
      };
    },
    hasAppendedContent() {
      return this.$slots.append || this.icon || this.appendText;
    },
    inputStyles() {
      return this.hasAppendedContent
        ? { paddingRight: this.rem(this.paddingRight) }
        : {};
    },
    // localMask() {
    //   const mask = this.mask;
    //   const typeOfMask = typeof mask;

    //   if (
    //     ["string", "function"].includes(typeOfMask) ||
    //     (Array.isArray(mask) && mask.length)
    //   ) {
    //     return mask;
    //   }

    //   return mask === null && Object.keys(mask).length < 1
    //     ? ""
    //     : createNumberMask(mask);
    // },
    localError() {
      return this.validator?.$error;
    },
    localErrorMessages() {
      return this.validator?.$errors.map((message) => {
        const id = { id: uuidv4() };
        return { ...message, ...id };
      });
    },
  },
  watch: {
    value(val) {
      this.localValue = val;
    },
  },
  mounted() {
    // this.hasAppendedContent && this.calcPaddings();
    this.hasAppendedContent;
  },
  methods: {
    uuidv4,
    // async calcPaddings() {
    //   await this.$nextTick();

    //   const { baseFontSize, currentFontSize } = getFontSizes();
    //   this.paddingRight =
    //     (this.$refs.append?.clientWidth * baseFontSize) / currentFontSize || 0;
    // },
    rem(pxValue) {
      return `${pxValue / 10}rem`;
    },
    onChange(e) {
      const value = e.target.value;
      this.localValue = value;
      /**
       * emits on change
       *
       * @event change
       * @property {string} input resulting input value
       */
      this.$emit("change", value);
    },
    onInput(e) {
      const value = e.target.value;
      this.localValue = value;
      /**
       * emits on input
       *
       * @event input
       * @property {string} input resulting input value
       */
      this.$emit("update:value", value);
    },
  },
};
</script>

<style scoped>
.ui-input__control {
  background-color: white;
  height: 41px;
  width: 100%;
  color: #353535;
}
._error {
  border-color: red;
}
</style>

